
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/symfony
    working_dir: /var/www/symfony
    environment:
      - DATABASE_URL=${DATABASE_URL:-mysql://upwork-tracker:12345678@mysql:3306/upwork-tracker}
      - APP_ENV=${APP_ENV:-dev}
      - APP_DEBUG=${APP_DEBUG:-1}
      - UPWORK_API_KEY=${UPWORK_API_KEY}
      - UPWORK_API_SECRET=${UPWORK_API_SECRET}
      - UPWORK_CALLBACK_URL=${UPWORK_CALLBACK_URL}
      - OPENAI_SECRET_KEY=${OPENAI_SECRET_KEY}
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: upwork-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upwork-tracker
      MYSQL_USER: upwork-tracker
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-12345678}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: upwork-tracker-phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

volumes:
  mysql_data: